### ISSUE TITLE
Vulnerabilities in OMD ?

### ISSUE THREAD

**Issue by heinowalther** [ConSol/omd#111]
Hi there,

We are running 3.30 Labs Edition on CentOS 7.  Everything is updated to latest versions.
We have a security scan that complains about some issues which I think are related to OMD...

1. PHP version (they recommend to upgrade PHP to 7.4.34) because of any vulnerabilities.
2. Apache version (they recommend to upgrade Apache to 2.4.44) again because of vulnerabilities.
3. OpenSSL version (they recommend to upgrade OpenSSL to 1.1.1g)
4. Disable HTTP TRACE Method for Apache

I guess it makes no sense to start upgrading apache, php etc. inside the OMD "jail" ?
Another solution could be to upgrade to a "Nightly" release or maybe even 4.0, but how stable is this?

Any other suggestions would be welcome.

/Heino

**Comment by sni** [comment]
1. OMD runs fine with php 7.x. You can simply update it with whatever tools your OS provides.
2. Same here, OMD does not have strict version dependencies. Simply update your sytem Apache. OMD does not ship its own.
3. Same here, OMD does not ship openssl, but uses the one already in place on the system. So just keep your OS up to date.
4. Thats probably something in the main system apache. OMD does not touch that apache configuration except it add an snippet to reverse proxy to the omd site. Securing the default system apache is out of scope for OMD. In OMD trace is disabled already.

Using the nightly probably won't make a difference, because neither apache, php or openssl is included and shiped with OMD. Version 4 does not change that. It might although help to update to centos 8 which comes with newer versions of the mentioned software.

**Comment by heinowalther** [comment]
Makes sense :-). Just thought OMD used its own packages... 

Problem solved, thanks :-)
