### ISSUE TITLE
Discussion: We'd like to add monitoring-agent plugins to OMD

### ISSUE THREAD

**Issue by infraweavers** [ConSol/omd#132]
Hi,

We've been running an internal project for the last few months to create an open-source, secure, permissively-licensed, cross-platform replacement for NRPE (on linux) and the NSClient WebServer (on Windows) (https://github.com/infraweavers/monitoring-agent) so we can have easier management etc (as well as working around the memory leaks in NSClient++ etc). We've just finished rolling it out production wide, currently it's only used by us so we understand if you're uncomfortable having something added essentially for a single user, however we are hoping that this could help open the door to it being more widely used.

To that end we'd like to add the client plugins:
- https://github.com/infraweavers/monitoring-agent-scripts  (base scripts, simple implementations)
- https://github.com/infraweavers/monitoring-agent-client (equivant of check_nrpe)
into OMD as we believe this could be of use to basically everyone if they are struggling with nrpe or nsclient and chose to switch over to monitoring-agent and make it easy to transition if chosen.

Open to feedback/thoughts!

**Comment by lausser** [comment]
Hi,
bad news first: no.
To be honest, we develop and maintain OMD because it is the toolbox we are using in our customer projects. Whenever we added a feature, it was driven by a specific need or the purpose to provide better service. Adding anything else would make it more and more difficult to keep track on things.
Your project looks not bad, i like that you keep an eye on easy installation and security. But we still have big NSClient++ installations (Memory leak will be fixed soon) and rely on check_by_ssh for Unix. So we won't use monitoring-agent for now.
Anyway, 3rd-party-plugins can easily be added to an OMD installation by simply dropping them into ~/local/lib/monitoring-plugins and referencing them with $USER2$.
Gerhard

**Comment by infraweavers** [comment]
Cool, thanks for the quick reply @lausser 

At current we deploy our plugins into $USER2$ like you said and we're happy to help out in any way if the perspective changes over time :)
