### ISSUE TITLE
Memory leakage after OMD upgrade 5.00

### ISSUE THREAD

**Issue by Vani2468** [ConSol/omd#149]
After OMD upgrade to 5.00, we have observed that more memory is using by chrome process (almost 400 process running at the back end where grafana is using) resulting more memory usage (~6GB). This causing the communication issue with service now due to low memory and not creating any tickets in servicenow.

Please find the attached chrome processes file.
[chromeprocess.txt](https://github.com/ConSol/omd/files/10401303/chromeprocess.txt)

Please find below entries from naemon.log file
66511 [1673515856] Unable to send check for service 'Gearman: Job server site1' on host 'nagios' to worker (ret=-2)
66512 [1673515858] Unable to send check for service 'Service Restart Log' on host 'localhost' to worker (ret=-2)
66527 [1673515864] Unable to send check for service 'Gearman: Worker - site2' on host 'nagios' to worker (ret=-2)
66543 [1673515871] Unable to send check for service 'Gearman: Worker - site3' on host 'nagios' to worker (ret=-2)
66545 [1673515872] Unable to send check for service 'Gearman: Worker - site4' on host 'nagios' to worker (ret=-2)
66546 [1673515872] Unable to send check for service 'Gearman: Worker - site5' on host 'nagios' to worker (ret=-2)
66549 [1673515874] Unable to send check for service 'Gearman: Job server site6' on host 'nagios' to worker (ret=-2)
66551 [1673515876] Unable to send check for service 'Gearman: Job server site1' on host 'nagios' to worker (ret=-2)
66552 [1673515879] Unable to send check for service 'Service Restart Log' on host 'localhost' to worker (ret=-2)

Kindly advice if this can be fixed.

**Comment by bfalgarvio** [comment]
Hi,

I'm also having issues with these grafana chrome processes but on 4.60.0. I was hoping to upgrade to 5.0.0 to solve this issue but it seems that there are other people with the same problem on the new version.
There are hundreds of chrome processes being created automatically on my server making the memory load increase a lot and sometimes making the server crash.

My server:
-SLES 12 (in order to upgrade to 5.0.0 I know that I have upgrade the OS to SLES 15)
-Grafana version 7.5.13
-Grafana Image Renderer Plugin - 3.6.2 (I tried older versions, like 2.1.1, but still got these hundreds of chrome processes being created)


How can we fix this issue? Is it any problem with the Grafana Image Renderer plugin or any extra configuration needed on grafana?

Would be good to get some feedback on this.

Thanks in advance!

**Comment by sni** [comment]
should be fixed with https://github.com/sni/Thruk/commit/c1611e2ba3cd71e6df86a6b08bc9a2ca82a3aa71
