### ISSUE TITLE
CVE-2024-38474 in Apache and UnsafeAllow3F addition

### ISSUE THREAD

**Issue by romanstech** [ConSol/omd#192]
RHEL8.10, OMD 5.4

After the latest RHEL update it's not possible to enter to OMD — receive 403 Forbidden.
It's because of new vulnerability CVE-2024-38474 in Apache. 
> Root Cause
> A substitution encoding issue in mod_rewrite allows an attacker to execute scripts in directories permitted by the configuration but not directly reachable by any URL or source disclosure of scripts meant only to be executed as CGI. This is the [CVE-2024-38474](https://access.redhat.com/security/cve/CVE-2024-38474).

Temporary solution:
Add **UnsafeAllow3F** flag to 1 row in file **etc/apache/conf.dthruk_cookie_auth.conf**:
`RewriteRule ^(.*)$                   ${users:$1|/loginbad/}  [C,NS,UnsafeAllow3F]`

Permanent solution:
**Update Apache in OMD to v.2.4.60+**

**Comment by sni** [comment]
thanks for reporting this. It should be fixed already in the nightly builds starting Aug 15th.
- 171c16f8a880564509b8cac91d9437b995e12caa

Seems like rhel patched a bit too hard because the error triggered even on pages not containing escaped question marks. So on rhel8/9 all pages fail with the error.
On newer Ubuntu systems only saving bookmarks in Thruk was broken. This has been fixed with
- https://github.com/sni/Thruk/commit/825dd5bdfffaa2d5afb3ab8e1e3459db8e881eaa
- https://github.com/sni/Thruk/discussions/1383

**Comment by romanstech** [comment]
Thank you very much!
________________________________

**Comment by romanstech** [comment]
In any case, amazing work! I used Nagios for years but now I really love using OMD.

**Comment by sni** [comment]
nightly builds are fine now and work with old/new apache versions.
