### ISSUE TITLE
Starting mkeventd with --snmptrap gives error

### ISSUE THREAD

**Issue by ingardm** [ConSol/omd#36]
/usr/bin/python /omd/sites/testsite/bin/mkeventd  --snmptrap
FATAL ERROR: No module named rfc1902

**Comment by firegore** [comment]
had the same Issue.

The Issue is that the used PySNMP Version is too old.

Workaround as for now:
Download a newer PySNMP Version (iirc >4.3)
You can get the newer .egg File from [PyPi PySNMP](https://pypi.python.org/pypi/pysnmp), drop the file into /omd/versions/<version>/lib/python and remove the old Version from the Folder.

Tested with the newest Nightly

**Comment by ingardm** [comment]
I solved it by installing the latest version of cmk raw and upgrading my site. With the added benefit of having more mobs included by default

**Comment by firegore** [comment]
If you install CMK Raw and then Upgrade the Site with it, you loose all the extra OMD-Labs Functions/Packages (Grafana, InfluxDB, Gearman, Naemon, etc...)
