### ISSUE TITLE
Check_MK EOL OMD 3

### ISSUE THREAD

**Issue by L4rS6** [ConSol/omd#74]
Hi

Is it right that check_mk won't be in the next OMD 3 release? As mentioned in the changelog:

```
DEPRECATION WARNING: the following components are deprecated and will be removed from the upcoming 3.x release:
          - Nagios 3
          - Icinga 1
          - CheckMK
          - Nagvis
```

What is the reason to drop it out? I couldn't find any information about that. Nagios 3 and Icinga 1 I understand, because there are new releases (Nagios 4 and Icinga 2) available.

**Comment by lausser** [comment]
Hi,
we (the OMD-Labs-Edition-Team, which is made up 100% of ConSol-employees) develop OMD partly in our free time, but mostly at work, driven by customer requirements. As among our customers there is not a single user of check_mk (au contraire, there are some former check_mk users, who switched to a Naemon/Thruk/Coshsh environment), we have no need for this tool. The same applies to nagvis. Only one has some Nagvis Dashboard for historical reasons, but those will soon be migrated to Thruk Dashboards.
This means: in order to provide the resources necessary to maintain, test and troubleshoot a check_mk package, we either need to become enthusiastic fans of check_mk (very unlikely) or somebody is willing to pay for it. If somebody definitively needs check_mk then there is still the Raw Edition of Mathias-Kettner-OMD.
Gerhard

**Comment by 4oo4** [comment]
Personally, I use check_mk to monitor a number of VPSes I run for web hosting and various other things, and it would be a huge effort to migrate to another tool, especially after investing time into creating custom checks after using it for several years.

I know that my check_mk site is a small install compared with others, and because I'm essentially using it as an individual developer, (instead of the majority of your customers who presumably have an actual IT budget to work with), depending on how costly it is for maintenance, I don't know if that's something I can afford. I would gladly pay what I'm able to, even though it probably wouldn't come close to what's needed to justify the investment of effort,  anyone else out there willing to contribute?

I can also provide some check_mk enthusiasm, and would be very happy to help with the work needed to maintain it if there are others who are able and willing to help. I might be alone in that, but if there are others out there who use it and want it maintained, please say something!

Cheers

**Comment by Muletia** [comment]
I have been trying to update OMD to include Check_MK v1.4.0p37 and I've got close, but there were packaging changes between v1.2.x and v1.4.x which have caused me some issues. We were hoping to use this version of OMD as a single integration of things like Grafana, Influxdb, potentially Naemon and Prometheus, as well as the other enhancements this version provides over the Check_MK Raw package.

**Comment by 4oo4** [comment]
@Muletia Thanks for working on that, what kind of challenges have you specifically encountered?

**Comment by lausser** [comment]
Hi,
it should be no problem to both install OMD-Labs-Edition and the Mathias-Kettner-Raw-Edition on a Server and then run two sites in parallel. One with a maintained check_mk and one with all the Thruk/Influx/Grafana/Prometheus..... stuff. 
Gerhard

**Comment by thizmo** [comment]
Hi,

we use OMD with check_mk in a not so small setup. Mostly because we have many different sites, maintained by many different people and different requirements. And one "uber"-site which lists all the content for a single view.

Today i was a bit shocked that Check_MK will be dropped (so soon).  Yet i can totaly understand the explanation. 

Questions:
- Is there an alternative with Thruk that allows the same mgmt of different sites with different people and different skill sets?  Sorry, i am not familiar with Thruk at all.
- What would it mean/cost to become a customer and pay for further integration? 

Also i can totally relate to @4oo4 since we have also invested a lot of time into this setup. Yet contribution is somewhat difficult since we are only implement and maintain the setup over the years. 

Thx a lot in advance.

**Comment by IvanRossi** [comment]
We have a very similar use caseas @thizmo and we are willing to contribute some work and/or money 
to keep Check_MK in.

> Hi,
> 
> we use OMD with check_mk in a not so small setup. Mostly because we have many different sites, maintained by many different people and different requirements. And one "uber"-site which lists all the content for a single view.
> 
> Today i was a bit shocked that Check_MK will be dropped (so soon). Yet i can totaly understand the explanation.
> 
> Questions:
> 
>     * Is there an alternative with Thruk that allows the same mgmt of different sites with different people and different skill sets?  Sorry, i am not familiar with Thruk at all.
> 
>     * What would it mean/cost to become a customer and pay for further integration?
> 
> 
> Also i can totally relate to @4oo4 since we have also invested a lot of time into this setup. Yet contribution is somewhat difficult since we are only implement and maintain the setup over the years.
> 
> Thx a lot in advance.

**Comment by L4rS6** [comment]
We also use check_mk with quite a lot of hosts (>1500) and services (> 35000). The main reason we use check_mk is the agent based monitoring and its easily configuration with tags and so on. In addition we use mod-gearman for check execution, because we had a lot of performance issues without mod-gearman (e.g. growing nagios process after loading historical data in check_mk). I'm also willing to contribute some work to keep check_mk in.

**Comment by digitalcardboard** [comment]
I'm coming into this a little late, so my apologies...

Is there a migration path from check_mk to Naemon/Thruk/Coshsh? Specifically, we're using check_mk_agent for a number of additional monitoring things, and I'd like to be able to continue using those in some fashion. I've also become accustomed to how check_mk rolls up all the checks in a single call rather than individual calls.

I'm not against moving, but would definitely want a better understanding of how to get there.

**Comment by sni** [comment]
you might either use check_mk raw, which is a OMD flavour with cmk (but only cmk and nothing else). Or you (or someone else) might try to local install cmk into your OMD site. Although i am not sure this is possibly with reasonable effort.
