### ISSUE TITLE
Missing Packages for SLES 12 SP4 and SLES 15  SP1

### ISSUE THREAD

**Issue by mobitux** [ConSol/omd#90]
Are there any intentions to release packages for SLES 12 SP4 and SLES 15 SP1?

**Comment by sni** [comment]
Right now, there are no plans for those. SLES is always a bit difficult and time consuming, because there are no public repositories. So usually we create them on demand whenever our customers ask for it.

**Comment by lausser** [comment]
Not yet. As soon as one of our customers is using one of these releases or 
as soon as somebody signs a support contract so enough funding is available 
for porting and running the build infrastructure.

Gerhard



Von: Michael Niewiara [mailto:notifications@github.com]
Gesendet: Mittwoch, 9. Oktober 2019 15:26
An: ConSol/omd <omd@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [ConSol/omd] Missing Packages for SLES 12 SP4 and SLES 15 SP1 (#90)



Are there any intentions to release packages for SLES 12 SP4 and SLES 15 
SP1?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
<https://github.com/ConSol/omd/issues/90?email_source=notifications&email_token=AABQSOD2YWZESVO2QELINLDQNXLWXA5CNFSM4I67M2A2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HQULZGA> 
, or mute the thread

**Comment by Johngoutbeck** [comment]
I to have clients that would like to have this running on SLES 12 SP4, SP5 and on SLES 15 SP1 (and SP2 when it comes out -very soon)

Thanks & great product for my clients
