### ISSUE TITLE
Non-packaged Prometheus documentation

### ISSUE THREAD

**Issue by secustor** [ConSol/omd#98]
We are using a distributed query layer for our Prometheus instances, [Thanos](https://github.com/thanos-io/thanos) to be precise.

The documentation and parameters suggest that only a bundled Prometheus can be used. 
But a quick search through the code base, especially the Apache configuration, indicate that it is possible. 

Is this scenario in supported at the moment? 

If not, would you accept PRs for this?

**Comment by sni** [comment]
What exactly is the issue? You can use Thanos with the Prometheus in OMD. In fact we do that, but
we did not integrate Thanos in OMD yet because its pita to build from source. Instead there is a
`bin/get_thanos` script which simply downloads thanos.
Pull requests are welcome, for example to add thanos init scripts or anything thats required to run thanos in OMD.

**Comment by secustor** [comment]
Thx for the quick answer!

My plan would be to not use the packaged Prometheus and instead forward the queries to our Thanos instance which is hosted in a K8 cluster. 
I think what you mean is hosting a Thanos Query Layer on the OMD host or maybe I`m missing something here.

**Comment by sni** [comment]
If you are not using the packaged prometheus from OMD, then i don't get it. What is the issue with OMD?
